///////////////////////////////////////////////////////////
//  ChatHandler.cs
//  Implementation of the Class ChatHandler
//  Generated by Enterprise Architect
//  Created on:      12-ápr.-2013 16:12:57
//  Original author: hallgato
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace BattleshipClient {

	public class ChatHandler : IChatSystem {

		private PortSender ps;

		public ChatHandler(PortSender psa) {
			ps = psa;
		}

		public List<string> GetNewMsgs() {
			List<string> valasz = new List<string>();
			return valasz;
		}

		/// 
		/// <param name="Message"></param>
		public void SendMsg(string Message) {

		}

	}//end ChatHandler
}