///////////////////////////////////////////////////////////
//  ChatHandler.cs
//  Implementation of the Class ChatHandler
//  Generated by Enterprise Architect
//  Created on:      12-ápr.-2013 16:12:57
//  Original author: hallgato
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace BattleshipClient {

	public class ChatHandler : IChatSystem {

		private PortSender ps;

		public ChatHandler(PortSender psa) {
			ps = psa;
		}

		public List<string> GetNewMsgs() {
			List<string> valasz = new List<string>();
            object[] args = new object[1];
            args[0] = valasz;
            ps.Send("chatsystem", "GetNewMsgs", args);
            return valasz;
			
		}

		/// 
		/// <param name="Message"></param>
		public void SendMsg(string Message) {
            object[] args = new object[1];
            args[0] = Message;
            ps.Send("chatsystem", "SendMsg", args);
		}

	}//end ChatHandler
}