///////////////////////////////////////////////////////////
//  IHitDetector.cs
//  Implementation of the Interface IHitDetector
//  Generated by Enterprise Architect
//  Created on:      12-ápr.-2013 16:39:35
//  Original author: Feanor
///////////////////////////////////////////////////////////



namespace BattleshipClient {
	public interface IHitDetector {

		GameBoard GetEnemyShot();

		/// 
		/// <param name="ShootY"></param>
		/// <param name="ShootX"></param>
		GameBoard Shoot(int ShootX, int ShootY);
	}//end IHitDetector
}